discourse_index_now:
  indexnow_enabled:
    default: false
    client: true
    validator: "DiscourseIndexNow::EnabledValidator"
  indexnow_api_key:
    default: ""
    client: false
    validator: "DiscourseIndexNow::ApiKeyValidator"
  indexnow_submit_on_create:
    default: true
    client: false
  indexnow_submit_on_edit:
    default: true
    client: false
  indexnow_submit_on_reply:
    default: false
    client: false
  indexnow_url_cooldown_minutes:
    default: 1
    min: 0
    client: false
  indexnow_excluded_category_ids:
    type: category_list
    default: ""
    client: false
  indexnow_excluded_tag_names:
    type: tag_list
    default: ""
    client: false
  indexnow_hourly_limit:
    default: 200
    client: false
  indexnow_daily_limit:
    default: 10000
    client: false
